[package]
name = "irxrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "irxrs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
